//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdditionalActivities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdditionalActivities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horas acumuladas.
        /// </summary>
        internal static string accHours {
            get {
                return ResourceManager.GetString("accHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atividades.
        /// </summary>
        internal static string activities {
            get {
                return ResourceManager.GetString("activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorias.
        /// </summary>
        internal static string activityCategories {
            get {
                return ResourceManager.GetString("activityCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atividades.
        /// </summary>
        internal static string activityItems {
            get {
                return ResourceManager.GetString("activityItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AddAct_icon1 {
            get {
                object obj = ResourceManager.GetObject("AddAct icon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprovação.
        /// </summary>
        internal static string approvation {
            get {
                return ResourceManager.GetString("approvation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificado.
        /// </summary>
        internal static string certif {
            get {
                return ResourceManager.GetString("certif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curso.
        /// </summary>
        internal static string course {
            get {
                return ResourceManager.GetString("course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horas deferidas.
        /// </summary>
        internal static string defHours {
            get {
                return ResourceManager.GetString("defHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data da entrega.
        /// </summary>
        internal static string delDate {
            get {
                return ResourceManager.GetString("delDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        internal static string desc {
            get {
                return ResourceManager.GetString("desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data da avaliação.
        /// </summary>
        internal static string evalDate {
            get {
                return ResourceManager.GetString("evalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avaliador.
        /// </summary>
        internal static string evaluator {
            get {
                return ResourceManager.GetString("evaluator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horas.
        /// </summary>
        internal static string hours {
            get {
                return ResourceManager.GetString("hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passo de horas.
        /// </summary>
        internal static string hourStep {
            get {
                return ResourceManager.GetString("hourStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horas máximas.
        /// </summary>
        internal static string maxHours {
            get {
                return ResourceManager.GetString("maxHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horas mínimas.
        /// </summary>
        internal static string minHours {
            get {
                return ResourceManager.GetString("minHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observação.
        /// </summary>
        internal static string obs {
            get {
                return ResourceManager.GetString("obs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portifólios.
        /// </summary>
        internal static string portfolios {
            get {
                return ResourceManager.GetString("portfolios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prontuário.
        /// </summary>
        internal static string regNumber {
            get {
                return ResourceManager.GetString("regNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado da matrícula.
        /// </summary>
        internal static string regState {
            get {
                return ResourceManager.GetString("regState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regras.
        /// </summary>
        internal static string rules {
            get {
                return ResourceManager.GetString("rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível salvar..
        /// </summary>
        internal static string saveError {
            get {
                return ResourceManager.GetString("saveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horas pleiteadas.
        /// </summary>
        internal static string schedHours {
            get {
                return ResourceManager.GetString("schedHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semestre.
        /// </summary>
        internal static string semester {
            get {
                return ResourceManager.GetString("semester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alunos.
        /// </summary>
        internal static string students {
            get {
                return ResourceManager.GetString("students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ano.
        /// </summary>
        internal static string year {
            get {
                return ResourceManager.GetString("year", resourceCulture);
            }
        }
    }
}
